version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.chonky-frontend
    image: frontend
    ports:
      - "3000:3000"